language: php

services:
  - mysql

jobs:
  fast_finish: true
  include:
    - env: DBTYPE=mysql; MW=1.31.3; SMW=3.1.0
      php: 7.1
    - env: DBTYPE=sqlite; MW=1.33.2; SMW=3.1.0
      php: 7.2
    - env: DBTYPE=mysql; MW=1.34.0; SMW=dev-master; TYPE=coverage
      php: 7.3
    - env: DBTYPE=mysql; MW=master
      php: 7.4
  allow_failures:
    # Started failing August 2020 for unknown reason, perhaps will recover on its own
    - env: DBTYPE=mysql; MW=master
      php: 7.4


install:
  - travis_retry composer self-update
  - bash .travis.install.sh

script: ../phase3/tests/phpunit/phpunit.php -c ../phase3/extensions/Maps/phpunit.xml.dist

after_success:
  - if [[ "$TYPE" != "coverage" ]]; then exit 0; fi
  - ../phase3/tests/phpunit/phpunit.php -c ../phase3/extensions/Maps/phpunit.xml.dist --coverage-clover coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
    - $HOME/.composer/cache
